### ISSUE TITLE
ImportError: PyCapsule_Import could not import module "datetime"

### ISSUE THREAD

**Issue by mankoff** [nbren12/call_py_fort#23]
Thank you for developing this neat-looking package. I'm hoping to use it with the our GCM.

I've run the examples successfully. I'm now trying to embed the simplest example, with no associated python file, into the GCM. That is, I've added this to a FORTRAN file:

```fortran
#ifdef CALLPY
      a(:) = 99999.9
      call set_state("a", a)
      call call_function("builtins", "print")
C     read any changes from "a" back into a.
      call get_state("a", a)
#endif
```

And at the top of that file,

```fortran
#ifdef CALLPY
      use callpy_mod
#endif
...
real(8) :: a(10)
```

 I have the code linking and compiling, but it crashes when I run with a fairly generic Python error.

<details><summary>Crash Report</summary>

<pre>

Failed to initialize the Python-CFFI embedding logic:

Traceback (most recent call last):
  File "/home/kdm/local/mambaforge/envs/fort2py/lib/python3.11/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/kdm/local/mambaforge/envs/fort2py/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/kdm/local/mambaforge/envs/fort2py/lib/python3.11/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: PyCapsule_Import could not import module "datetime"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kdm/local/mambaforge/envs/fort2py/lib/python3.11/site-packages/numpy/__init__.py", line 141, in <module>
Failed to initialize the Python-CFFI embedding logic:

Traceback (most recent call last):
    from . import core
  File "/home/kdm/local/mambaforge/envs/fort2py/lib/python3.11/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/usr/bin/python3"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: PyCapsule_Import could not import module "datetime"

From: my_plugin
compiled with cffi version: 1.15.1
_cffi_backend module: '/home/kdm/local/mambaforge/envs/fort2py/lib/python3.11/site-packages/_cffi_backend.cpython-311-x86_64-linux-gnu.so'
sys.path: ['/home/kdm/projects/GISS/call_py_fort/examples', '/home/kdm/projects/GISS/spack/var/spack/environments/tw-discover12/modele-control/lib', '/home/kdm/projects/GISS/spack/var/spack/environments/tw-discover12/pygiss', '/home/kdm/projects/GISS/spack/var/spack/environments/tw-discover12/opt/lib/python3.5/site-packages', '/home/kdm/projects/GISS/ModelE_Support/huge_space/r01', '/home/kdm/local/mambaforge/envs/fort2py/lib/python311.zip', '/home/kdm/local/mambaforge/envs/fort2py/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/home/kdm/local/mambaforge/envs/fort2py/lib/python3.11/site-packages']
</pre>

... and onward....

</details>

I've read the `IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!` document at https://numpy.org/devdocs/user/troubleshooting-importerror.html but still have not been able to make progress.

If you have any suggestions I would be grateful.

**Comment by mankoff** [comment]
Solved. I needed to add `export PYTHONPATH=/home/kdm/local/mambaforge/envs/fort2py/lib/python3.11/lib-dynload`
